version: '3.8'
services:
  bot-harina:
    build: .
    env_file: 
      - .env
    volumes:
      - .:/usr/src/app
    command: /bin/bash -c "python bot/harina.py"

networks:
  default:
    external:
      name: gemini-openai-proxy-network